version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todo_db
    ports:
      - 3333:3306
    volumes:
      - db:/var/lib/mysql

  gateway:
    depends_on:
      - mysqldb
    build: ./gateway
    restart: unless-stopped
    hostname: gateway
    ports:
      - 8000:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www

  auth:
    build: ./auth
    restart: always
    hostname: auth
    env_file:
      - .env
    links:
      - mysqldb
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www
#  todo:
#    build: ./todo
#    restart: always
#    hostname: todo
#    env_file:
#      - .env
#    links:
#      - mysqldb

volumes:
  db:
