version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todo_db
    ports:
      - 3333:3306
    volumes:
      - db:/var/lib/mysql

  todo:
    depends_on:
      - mysqldb
    working_dir: /app/todo
    build:
      context: ./todo
      dockerfile: Dockerfile
    container_name: todo
    restart: unless-stopped
    hostname: todo
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./todo:/app
      - /app/node_modules

  auth:
    depends_on:
      - mysqldb
    working_dir: /app/auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    restart: unless-stopped
    hostname: auth
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./auth:/app
      - /app/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - todo
      - auth
    ports:
      - "80:80"


volumes:
  db:
